[package]
name = "pidl-bud"
version = "0.1.1"
edition = "2021"

[dependencies]
higher-kinded-types = "0.1.1"
wasm_runtime_layer = { version = "0.4.2", optional = true }

[features]
wasm_runtime_layer = ["dep:wasm_runtime_layer"]
